version: '3.8'
services:
  sisyphus-backend:
    restart: always
    image: ${DOCKER_REGISTRY_URL}/${TAG_NAME}
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/sisyphus
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-default}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SISYPHUS_FRONTEND_HOSTNAME=${SISYPHUS_FRONTEND_HOSTNAME}
    depends_on:
      - mongodb
    networks:
      - app

  mongodb:
    restart: always
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app

volumes:
  mongodb_data:
  gradle-cache:

networks:
  app:
