FROM eclipse-temurin:21-jdk as build
WORKDIR /workspace/app

COPY build.gradle.kts settings.gradle.kts ./
COPY gradlew ./
COPY gradle ./gradle
COPY src ./src

RUN chmod +x ./gradlew
RUN ./gradlew check
