FROM eclipse-temurin:21-jdk

WORKDIR /workspace/app

COPY gradlew ./
COPY gradle gradle
COPY build.gradle.kts settings.gradle.kts ./

RUN chmod +x ./gradlew
RUN ./gradlew dependencies --no-daemon

COPY src ./src

CMD ["./gradlew", "bootRun", "--no-daemon", "--continuous"]
