version: '3.8'
services:
  sisyphus-backend:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    image: sisyphus-backend
    ports:
      - "8080:8080"
    volumes:
      - ${APP_VOLUME:-./}:/app
      - ${GRADLE_CACHE_VOLUME:-gradle-cache}:/root/.gradle
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/sisyphus
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-default}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app

volumes:
  mongodb_data:
  gradle-cache:

networks:
  app:
