logging.level.root: INFO
openai.api.key: 'test-openai-api-key'

spring:
  data:
    mongodb:
      host: localhost
      port: 2137
      database: test_db

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.11
