spring.application.name: adaptive_learning_companion
spring.data.mongodb.uri: mongodb://localhost:27017/adaptive_learning_companion

openai.api:
  model: "gpt-4o-mini"
  max_tokens: 500
  key: ${OPENAI_API_KEY}

logging.level.root: INFO

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.11
