spring.application.name: sisyphus-backend
spring.data.mongodb.uri: mongodb://localhost:27017/sisyphus

openai.api:
  model: "gpt-4o"
  max_tokens: 1000
  key: ${OPENAI_API_KEY}

logging.level.root: INFO

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.11
